"use client";

// Shared resolver for navigation and catalog icons. Common choices use the
// curated registry; user-validated custom Lucide names load separately.
import dynamic from "next/dynamic";
import {
  Activity,
  BookOpen,
  BarChart3,
  Building2,
  BriefcaseBusiness,
  Boxes,
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardList,
  CircleUserRound,
  Cloud,
  Code2,
  Database,
  FileText,
  FolderKanban,
  Gauge,
  Globe,
  Home,
  Layers,
  LifeBuoy,
  Mail,
  Megaphone,
  KeyRound,
  LayoutDashboard,
  Layers3,
  Map,
  Package,
  Palette,
  PanelsTopLeft,
  Plug,
  Puzzle,
  Rocket,
  Shield,
  ShoppingCart,
  Sigma,
  SlidersHorizontal,
  Table2,
  TerminalSquare,
  Target,
  Tags,
  UserCog,
  UsersRound,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const DynamicNavIcon = dynamic(() => import("./dynamic-nav-icon").then((module) => module.DynamicNavIcon), { ssr: false });

export const NAV_ICONS: Record<string, LucideIcon> = {
  Activity,
  BookOpen,
  BarChart3,
  Building2,
  BriefcaseBusiness,
  Boxes,
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardList,
  CircleUserRound,
  Cloud,
  Code2,
  Database,
  FileText,
  FolderKanban,
  Gauge,
  Globe,
  Home,
  Layers,
  LifeBuoy,
  Mail,
  Megaphone,
  KeyRound,
  LayoutDashboard,
  Layers3,
  Map,
  Package,
  Palette,
  PanelsTopLeft,
  Plug,
  Puzzle,
  Rocket,
  Shield,
  ShoppingCart,
  Sigma,
  SlidersHorizontal,
  Table2,
  Target,
  Tags,
  TerminalSquare,
  UserCog,
  UsersRound,
  Workflow,
  Wrench,
  Zap,
};

export function NavIcon({ name, className }: { name?: string; className?: string }) {
  const Cmp = name ? NAV_ICONS[name] : undefined;
  if (Cmp) return <Cmp className={className} size={18} strokeWidth={1.8} />;
  if (name) return <DynamicNavIcon name={name} className={className} />;
  return <span className={`inline-block h-4 w-4 ${className ?? ""}`} />;
}
